{
 "title": "Log Central",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Logs Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"} [5m])",
     "legendFormat": "{{source}}-{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (count_over_time({level=\"critical\"}[$__interval]))",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum by () (count_over_time({level=\"warning\"}[$__interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum by () (count_over_time({level=\"error\"}[$__interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "System Wide Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"syslog\"} |= ``"
    }
   ]
  },
  {
   "title": "Critical Logs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({level=\"critical\"} [$__interval])",
     "legendFormat": "{{source}}-Critical-Alarms"
    }
   ]
  },
  { "title": "$Node Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$Node Log Counts",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({source=\"$Node\"} [$__interval])",
     "legendFormat": "{{source}}-{{level}}"
    }
   ]
  },
  {
   "title": "$Node Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "{source=\"$Node\"} |= ``"
    }
   ]
  }
 ]
}