{
 "title": "Nokia SROS Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "Traffic Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "gnmic_sros_if_stats_in_octets", "legendFormat": "{{source}}:{{port_port_id}}" },
    { "expr": "gnmic_sros_if_stats_out_octets", "legendFormat": "{{source}}:{{port_port_id}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "gnmic_sros_cpu_cpu_usage", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnmic_sros_mem_total_in_use", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "$Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_cpu_usage{source=\"$Node\"}"
    }
   ]
  },
  {
   "title": "$Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_in_use{source=\"$Node\"}"
    }
   ]
  },
  {
   "title": "$Node Packets Ingress",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "gnmic_sros_if_stats_in_packets{source=\"$Node\"}",
     "legendFormat": "{{source}}::{{port_port_id}}"
    }
   ]
  },
  {
   "title": "$Node Packets Ingress",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "gnmic_sros_if_stats_out_packets{source=\"$Node\"}",
     "legendFormat": "{{source}}::{{port_port_id}}"
    }
   ]
  }
 ]
}