# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: admin
skip-verify: true
port: 57400
timeout: 10s
encoding: json_ietf

targets:
  pe1:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_cpu
      - sros_mem
      - sros_port_oper_state
      - sros_port_stats
      - sros_ipv4_stats
      - sros_ldp
      - sros_isis_oper_state
      - sros_isis_adjacency
      - sros_isis_global_stats
      - sros_bgp_stats
      - sros_bgp_up_peers
      - sros_bgp_neighbor_stats
      - sros_vpls_instance_global
      - sros_vpls_sap_sdp_oper_state
      - sros_vpls_traffic_stats_ingress
      - sros_vpls_traffic_stats_egress


  pe2:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_if_oper_state

  pe3:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_if_oper_state

  pe4:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_if_oper_state

  p1:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_if_oper_state

  p2:57400:
    insecure: true
    password: admin
    subscriptions:
      - sros_if_oper_state


subscriptions:

### System Performance ###

  sros_cpu:
    paths:
      - /state/system/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_mem:
    paths:
      - /state/system/memory-pools
    mode: stream
    stream-mode: sample
    sample-interval: 5s

### Port  ###
  sros_port_oper_state:
    paths:
      - /state/port[port-id=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s
  
  sros_port_stats:
    paths:
      - /state/port[port-id=*]/statistics
      - /state/port[port-id=*]/ethernet/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

### Routing Table ###

  sros_ipv4_stats:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s


### LDP Subscriptions ###
  
  sros_ldp:
    paths:
      - /state/router[router-name=Base]/ldp/ipv4-oper-state
      - /state/router[router-name=Base]/ldp/ipv4-up-time
      - /state/router[router-name=Base]/ldp/statistics/adjacency/ipv4
      - /state/router[router-name=Base]/ldp/statistics/targeted-peer/ipv4/
    mode: stream
    stream-mode: sample
    sample-interval: 5s 

### IGP Subscriptions ###
  sros_isis_oper_state:
    paths:
      - /state/router[router-name=Base]/isis[isis-instance=0]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_isis_adjacency:
    paths:
      - /state/router[router-name=Base]/isis[isis-instance=0]/interface[interface-name=*]/adjacency[adjacency-index=1]/oper-state
      - /state/router[router-name=Base]/isis[isis-instance=0]/interface[interface-name=*]/adjacency[adjacency-index=1]/uptime
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_isis_global_stats:
    paths:
      - /state/router[router-name=Base]/isis[isis-instance=0]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

### BGP Subscriptions ###

  sros_bgp_stats:
    paths:
      - /state/router[router-name=*]/bgp/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_up_peers:
    paths:
      - state/router[router-name=*]/bgp/convergence/family[family-type=ipv4]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_neighbor_stats:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

### VPLS Subscriptions ###

  sros_vpls_instance_global:
    paths:
      - /state/service/vpls[service-name=*]/oper-state
      - /state/service/vpls[service-name=*]/oper-service-id
      - /state/service/vpls[service-name=*]/sap-count
      - /state/service/vpls[service-name=*]/sdp-bind-count
    stream-mode: sample
    mode: stream
    sample-interval: 5s

  sros_vpls_sap_sdp_oper_state:
    paths:
      - /state/service/vpls[service-name=*]/sap[sap-id=*]/oper-state
      - /state/service/vpls[service-name=10]/spoke-sdp[sdp-bind-id=*]/oper-state
    stream-mode: on-change

  sros_vpls_traffic_stats_ingress:
    paths:
      - /state/service/vpls[service-name=*]/sap[sap-id=*]/ingress/qos/sap-ingress/traffic-manager
    stream-mode: sample
    mode: stream
    sample-interval: 5s
  
  sros_vpls_traffic_stats_egress:
    paths:
      - /state/service/vpls[service-name=*]/sap[sap-id=*]/egress/qos/sap-egress/traffic-manager
    stream-mode: sample
    mode: stream
    sample-interval: 5s


outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
