{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "route": {
      "receiver": "discord-dallas-dc",
      "group_by": [
        "grafana_folder",
        "alertname"
      ]
    },
    "templates": null,
    "receivers": [
      {
        "name": "discord-dallas-dc",
        "grafana_managed_receiver_configs": [
          {
            "uid": "c3cefb62-a03e-4e42-9dad-9aebaccfcb9f",
            "name": "discord-dallas-dc",
            "type": "discord",
            "disableResolveMessage": false,
            "settings": {
              "url": "https://discord.com/api/webhooks/1374613963106553907/ZsZ3nvjtzFRIoS9IVT3qx-t9ZZV2jklc9pBHHEimroIiPSCKxQv8TLLeHhFmvLvaS4Lz",
              "use_discord_username": false
            },
            "secureFields": {}
          }
        ]
      }
    ]
  }
}